### ISSUE TITLE
pretty print crashes when there is no log level

### ISSUE THREAD

**Issue by hbarcelos** [gajus/roarr#1]
My code:

```javascript
const log = require('roarr').default

log('foo')
```

If I run:

```
node index.js
```

it works just fine:

```json
{"context":{},"message":"foo","sequence":0,"time":1507231220906,"version":"1.0.0"}
```
---

However, if I run

```
node index.js | $(npm bin)/roarr pretty-print
```

I get the following error:

```
    var logLevel = message.context.logLevel.toUpperCase();
                                           ^
TypeError: Cannot read property 'toUpperCase' of undefined
    at DestroyableTransform.mapper (/home/henrique/labs/roarr-test/node_modules/roarr/dist/bin/commands/pretty-print.js:52:44)
    at DestroyableTransform.transform [as _transform] (/home/henrique/labs/roarr-test/node_modules/split2/index.js:33:21)
    at DestroyableTransform.Transform._read (/home/henrique/labs/roarr-test/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/home/henrique/labs/roarr-test/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/home/henrique/labs/roarr-test/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/home/henrique/labs/roarr-test/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (/home/henrique/labs/roarr-test/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
```

**Comment by gajus** [comment]
Fixed.

```bash
$ curiosity~/Documents/dev/gajus/roarr(master|✚1) % echo '{"context":{},"message":"foo","sequence":0,"time":1507231220906,"version":"1.0.0"}' | babel-node src/bin/index.js pretty-print
[2017-10-05T19:20:20.906Z]: foo
curiosity~/Documents/dev/gajus/roarr(master|✚1) %

```
