### ISSUE TITLE
version 7.1.0 started giving compile errors

### ISSUE THREAD

**Issue by vrecan** [gajus/roarr#58]
I was logging with the following format:

```
import { Roarr as log } from 'roarr';

try {
 doSomething();
} catch (err) {
  log.error({err}, "Something failed");
}
```
I did not update anything and this use to work, I am guessing a new patch version came out that changed the compile behavior making this no longer valid. 

package.json looks like this:
```
"roarr": "^7.1.0",
```

Was this intentional? It seems odd to have a breaking change like this on a patch version?

```
/var/runtime/app/node_modules/ts-node/src/index.ts:750
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/middleware/index.ts(49,9): error TS2769: No overload matches this call.
  Overload 1 of 2, '(context: { [x: string]: JsonValue<{}> | undefined; }, message: string, c?: SprintfArgument | undefined, d?: SprintfArgument | undefined, e?: SprintfArgument | undefined, f?: SprintfArgument | undefined, g?: SprintfArgument | undefined, h?: SprintfArgument | undefined, i?: SprintfArgument | undefined, j?: SprintfArgument | undefined): void', gave the following error.
    Type 'unknown' is not assignable to type 'JsonValue<{}> | undefined'.
      Type 'unknown' is not assignable to type '{ [x: string]: JsonValue<{}> | undefined; }'.
  Overload 2 of 2, '(message: string, b?: SprintfArgument | undefined, c?: SprintfArgument | undefined, d?: SprintfArgument | undefined, e?: SprintfArgument | undefined, f?: SprintfArgument | undefined, g?: SprintfArgument | undefined, h?: SprintfArgument | undefined, i?: SprintfArgument | undefined, j?: SprintfArgument | undefined): void', gave the following error.
    Argument of type '{ error: unknown; }' is not assignable to parameter of type 'string'.

    at createTSError (/var/runtime/app/node_modules/ts-node/src/index.ts:750:12)
    at reportTSError (/var/runtime/app/node_modules/ts-node/src/index.ts:754:19)
    at getOutput (/var/runtime/app/node_modules/ts-node/src/index.ts:941:36)
    at Object.compile (/var/runtime/app/node_modules/ts-node/src/index.ts:1243:30)
    at Module.m._compile (/var/runtime/app/node_modules/ts-node/src/index.ts:1370:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/var/runtime/app/node_modules/ts-node/src/index.ts:1374:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/var/runtime/app/src/server.ts:45:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (/var/runtime/app/node_modules/ts-node/src/index.ts:1371:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/var/runtime/app/node_modules/ts-node/src/index.ts:1374:12) {
  diagnosticText: 'src/middleware/index.ts(49,9): error TS2769: No overload matches this call.\n' +
    "  Overload 1 of 2, '(context: { [x: string]: JsonValue<{}> | undefined; }, message: string, c?: SprintfArgument | undefined, d?: SprintfArgument | undefined, e?: SprintfArgument | undefined, f?: SprintfArgument | undefined, g?: SprintfArgument | undefined, h?: SprintfArgument | undefined, i?: SprintfArgument | undefined, j?: SprintfArgument | undefined): void', gave the following error.\n" +
    "    Type 'unknown' is not assignable to type 'JsonValue<{}> | undefined'.\n" +
    "      Type 'unknown' is not assignable to type '{ [x: string]: JsonValue<{}> | undefined; }'.\n" +
    "  Overload 2 of 2, '(message: string, b?: SprintfArgument | undefined, c?: SprintfArgument | undefined, d?: SprintfArgument | undefined, e?: SprintfArgument | undefined, f?: SprintfArgument | undefined, g?: SprintfArgument | undefined, h?: SprintfArgument | undefined, i?: SprintfArgument | undefined, j?: SprintfArgument | undefined): void', gave the following error.\n" +
    "    Argument of type '{ error: unknown; }' is not assignable to parameter of type 'string'.\n"
```

**Comment by gajus** [comment]
That was never valid. It worked by accident.

If you wish to pass custom objects (such as Error), you need to provide serializers for them, e.g.

https://github.com/gajus/roarr#child

The way I handle the above scenario is:

```ts
import { Roarr as log } from 'roarr';
import { serializeError } from 'serialize-error';

try {
 doSomething();
} catch (err) {
  log.error({err: serializeError(err)}, "Something failed");
}
```
