### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by dmiwell** [gajus/roarr#79]
This happens during jest tests run after upgrading to `slonik=33.3.1` and `roarr=7.15.0`. There is memory leaking issue in the case.

Stack given:
```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:587:17)
    at Socket.addListener (node:events:605:10)
    at Socket.Readable.on (node:internal/streams/readable:887:35)
    at createNodeWriter (/node_modules/roarr/src/factories/createNodeWriter.ts:16:10)
    at createRoarrInitialGlobalState (/node_modules/roarr/src/factories/createRoarrInitialGlobalState.ts:43:32)
    at Object.<anonymous> (/node_modules/roarr/src/Roarr.ts:30:44)
    at Runtime._execModule (/node_modules/jest-runtime/build/index.js:1429:24)
    at Runtime._loadModule (/node_modules/jest-runtime/build/index.js:1013:12)
    at Runtime.requireModule (/node_modules/jest-runtime/build/index.js:873:12)
    at Runtime.requireModuleOrMock (/node_modules/jest-runtime/build/index.js:1039:21)
    at Object.<anonymous> (/node_modules/slonik/src/Logger.ts:1:1)
    at Runtime._execModule (/node_modules/jest-runtime/build/index.js:1429:24)
    at Runtime._loadModule (/node_modules/jest-runtime/build/index.js:1013:12)
    at Runtime.requireModule (/node_modules/jest-runtime/build/index.js:873:12)
    at Runtime.requireModuleOrMock (/node_modules/jest-runtime/build/index.js:1039:21)
    at Object.<anonymous> (/node_modules/slonik/src/utilities/parseDsn.ts:1:1)
    at Runtime._execModule (/node_modules/jest-runtime/build/index.js:1429:24)
    at Runtime._loadModule (/node_modules/jest-runtime/build/index.js:1013:12)
    at Runtime.requireModule (/node_modules/jest-runtime/build/index.js:873:12)
    at Runtime.requireModuleOrMock (/node_modules/jest-runtime/build/index.js:1039:21)
    at Object.<anonymous> (/node_modules/slonik/src/utilities/index.ts:9:1)
    at Runtime._execModule (/node_modules/jest-runtime/build/index.js:1429:24)
    at Runtime._loadModule (/node_modules/jest-runtime/build/index.js:1013:12)
    at Runtime.requireModule (/node_modules/jest-runtime/build/index.js:873:12)
    at Runtime.requireModuleOrMock (/node_modules/jest-runtime/build/index.js:1039:21)
    at Object.<anonymous> (/node_modules/slonik/src/connectionMethods/any.ts:2:1)
    at Runtime._execModule (/node_modules/jest-runtime/build/index.js:1429:24)
    at Runtime._loadModule (/node_modules/jest-runtime/build/index.js:1013:12)
    at Runtime.requireModule (/node_modules/jest-runtime/build/index.js:873:12)
    at Runtime.requireModuleOrMock (/node_modules/jest-runtime/build/index.js:1039:21)
    at Object.<anonymous> (/node_modules/slonik/src/connectionMethods/index.ts:1:1)
    at Runtime._execModule (/node_modules/jest-runtime/build/index.js:1429:24)
    at Runtime._loadModule (/node_modules/jest-runtime/build/index.js:1013:12)
    at Runtime.requireModule (/node_modules/jest-runtime/build/index.js:873:12)
    at Runtime.requireModuleOrMock (/node_modules/jest-runtime/build/index.js:1039:21)
    at Object.<anonymous> (/node_modules/slonik/src/binders/bindPool.ts:1:1)
    at Runtime._execModule (/node_modules/jest-runtime/build/index.js:1429:24)
    at Runtime._loadModule (/node_modules/jest-runtime/build/index.js:1013:12)
    at Runtime.requireModule (/node_modules/jest-runtime/build/index.js:873:12)
    at Runtime.requireModuleOrMock (/node_modules/jest-runtime/build/index.js:1039:21)
    at Object.<anonymous> (/node_modules/slonik/src/binders/index.ts:1:1)
    at Runtime._execModule (/node_modules/jest-runtime/build/index.js:1429:24)
    at Runtime._loadModule (/node_modules/jest-runtime/build/index.js:1013:12)
    at Runtime.requireModule (/node_modules/jest-runtime/build/index.js:873:12)
    at Runtime.requireModuleOrMock (/node_modules/jest-runtime/build/index.js:1039:21)
    at Object.<anonymous> (/node_modules/slonik/src/factories/createConnection.ts:1:1)
    at Runtime._execModule (/node_modules/jest-runtime/build/index.js:1429:24)
    at Runtime._loadModule (/node_modules/jest-runtime/build/index.js:1013:12)
    at Runtime.requireModule (/node_modules/jest-runtime/build/index.js:873:12)
    at Runtime.requireModuleOrMock (/node_modules/jest-runtime/build/index.js:1039:21)
    at Object.<anonymous> (/node_modules/slonik/src/factories/index.ts:1:1)
    at Runtime._execModule (/node_modules/jest-runtime/build/index.js:1429:24)
    at Runtime._loadModule (/node_modules/jest-runtime/build/index.js:1013:12)
    at Runtime.requireModule (/node_modules/jest-runtime/build/index.js:873:12)
    at Runtime.requireModuleOrMock (/node_modules/jest-runtime/build/index.js:1039:21)
    at Object.<anonymous> (/node_modules/slonik/src/index.ts:1:1)
    at Runtime._execModule (/node_modules/jest-runtime/build/index.js:1429:24)
    at Runtime._loadModule (/node_modules/jest-runtime/build/index.js:1013:12)
    at Runtime.requireModule (/node_modules/jest-runtime/build/index.js:873:12)
    at Runtime.requireModuleOrMock (/node_modules/jest-runtime/build/index.js:1039:21)
    at Object.<anonymous> (/node_modules/slonik-sql-tag-raw/src/utilities/interpolateNamedParameterReferences.ts:4:1)
    at Runtime._execModule (/node_modules/jest-runtime/build/index.js:1429:24)
    at Runtime._loadModule (/node_modules/jest-runtime/build/index.js:1013:12)
    at Runtime.requireModule (/node_modules/jest-runtime/build/index.js:873:12)
    at Runtime.requireModuleOrMock (/node_modules/jest-runtime/build/index.js:1039:21)
    at Object.<anonymous> (/node_modules/slonik-sql-tag-raw/src/utilities/index.ts:1:1)
    at Runtime._execModule (/node_modules/jest-runtime/build/index.js:1429:24)
    at Runtime._loadModule (/node_modules/jest-runtime/build/index.js:1013:12)
    at Runtime.requireModule (/node_modules/jest-runtime/build/index.js:873:12)
    at Runtime.requireModuleOrMock (/node_modules/jest-runtime/build/index.js:1039:21)
    at Object.<anonymous> (/node_modules/slonik-sql-tag-raw/src/sqlTags/raw.ts:8:1)
    at Runtime._execModule (/node_modules/jest-runtime/build/index.js:1429:24)
    at Runtime._loadModule (/node_modules/jest-runtime/build/index.js:1013:12)
    at Runtime.requireModule (/node_modules/jest-runtime/build/index.js:873:12)
    at Runtime.requireModuleOrMock (/node_modules/jest-runtime/build/index.js:1039:21)

```

**Comment by schongabor** [comment]
+1

**Comment by gajus** [comment]
I was able to replicate the issue. Investigating.

**Comment by gajus** [comment]
Opened an issue with Jest. I am not sure what is causing the memory leak warning or how to mitigate it.

https://github.com/jestjs/jest/issues/14580
